import { supabase } from './supabase';
import { Product, ProductStats } from '../types';

export const SAMPLE_PRODUCTS: Product[] = [];

export const PRESET_JEWELLERY_IMAGES = [
  {
    name: 'Floral Pearl Studs',
    category: 'Earrings',
    url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Gold Drop Earrings',
    category: 'Earrings',
    url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Leaf Diamond Studs',
    category: 'Earrings',
    url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Layered Gold Chain',
    category: 'Chains',
    url: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Eternity Solitaire Ring',
    category: 'Rings',
    url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Kundan Choker Necklace',
    category: 'Necklaces',
    url: 'https://images.unsplash.com/photo-1611591477287-db65bf4e3c98?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Gold Link Bracelet',
    category: 'Bracelets',
    url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&auto=format&fit=crop&q=80',
  },
  {
    name: 'Emerald Teardrop Pendant',
    category: 'Pendants',
    url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&auto=format&fit=crop&q=80',
  },
];

export const SUPABASE_UNIFIED_SCHEMA_SQL = `-- ==============================================================================
-- MY B SHOPPY - UNIFIED SUPABASE DATABASE SCHEMA (PRODUCTS & COD ORDERS)
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN.
-- Both tables share matching price, variant, quantity, and metadata structures.
-- ==============================================================================

-- 1. ENABLE EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 2. PRODUCTS TABLE SCHEMA
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT,
  title TEXT NOT NULL DEFAULT '',
  name TEXT,
  sku TEXT,
  category TEXT DEFAULT 'General',
  cover_image TEXT,
  image_url TEXT,
  mrp NUMERIC DEFAULT 0,
  sale_price NUMERIC NOT NULL DEFAULT 0,
  price NUMERIC DEFAULT 0,
  price_per_unit NUMERIC DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 0,
  stock INTEGER DEFAULT 0,
  badges JSONB DEFAULT '[]'::jsonb,
  description TEXT,
  material TEXT,
  -- Shared storefront-compatible columns (my B shoppy frontend)
  subtitle TEXT,
  original_price NUMERIC,
  category_id TEXT,
  badge TEXT,
  rating NUMERIC DEFAULT 5.0,
  reviews_count INTEGER DEFAULT 0,
  stone TEXT,
  variants JSONB DEFAULT '[]'::jsonb,
  in_stock BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Unique index on slug (allows multiple NULLs) so the frontend can upsert its catalog safely
CREATE UNIQUE INDEX IF NOT EXISTS products_slug_uniq ON public.products(slug);

-- Ensure all product columns exist safely (idempotent migration)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='title') THEN
    ALTER TABLE public.products ADD COLUMN title TEXT DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='name') THEN
    ALTER TABLE public.products ADD COLUMN name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='sku') THEN
    ALTER TABLE public.products ADD COLUMN sku TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='category') THEN
    ALTER TABLE public.products ADD COLUMN category TEXT DEFAULT 'General';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='cover_image') THEN
    ALTER TABLE public.products ADD COLUMN cover_image TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='image_url') THEN
    ALTER TABLE public.products ADD COLUMN image_url TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='mrp') THEN
    ALTER TABLE public.products ADD COLUMN mrp NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='sale_price') THEN
    ALTER TABLE public.products ADD COLUMN sale_price NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='price') THEN
    ALTER TABLE public.products ADD COLUMN price NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='price_per_unit') THEN
    ALTER TABLE public.products ADD COLUMN price_per_unit NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='quantity') THEN
    ALTER TABLE public.products ADD COLUMN quantity INTEGER DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='stock') THEN
    ALTER TABLE public.products ADD COLUMN stock INTEGER DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='badges') THEN
    ALTER TABLE public.products ADD COLUMN badges JSONB DEFAULT '[]'::jsonb;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='description') THEN
    ALTER TABLE public.products ADD COLUMN description TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='material') THEN
    ALTER TABLE public.products ADD COLUMN material TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='slug') THEN
    ALTER TABLE public.products ADD COLUMN slug TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='subtitle') THEN
    ALTER TABLE public.products ADD COLUMN subtitle TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='original_price') THEN
    ALTER TABLE public.products ADD COLUMN original_price NUMERIC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='category_id') THEN
    ALTER TABLE public.products ADD COLUMN category_id TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='badge') THEN
    ALTER TABLE public.products ADD COLUMN badge TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='rating') THEN
    ALTER TABLE public.products ADD COLUMN rating NUMERIC DEFAULT 5.0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='reviews_count') THEN
    ALTER TABLE public.products ADD COLUMN reviews_count INTEGER DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='stone') THEN
    ALTER TABLE public.products ADD COLUMN stone TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='variants') THEN
    ALTER TABLE public.products ADD COLUMN variants JSONB DEFAULT '[]'::jsonb;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='in_stock') THEN
    ALTER TABLE public.products ADD COLUMN in_stock BOOLEAN DEFAULT true;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='products_slug_uniq') THEN
    CREATE UNIQUE INDEX products_slug_uniq ON public.products(slug);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='created_at') THEN
    ALTER TABLE public.products ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='updated_at') THEN
    ALTER TABLE public.products ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();
  END IF;

  -- Relax strict not-null constraints if present
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='name' AND is_nullable='NO') THEN
    ALTER TABLE public.products ALTER COLUMN name DROP NOT NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='title' AND is_nullable='NO') THEN
    ALTER TABLE public.products ALTER COLUMN title DROP NOT NULL;
  END IF;
END $$;


-- ==============================================================================
-- 3. ORDERS TABLE SCHEMA (WITH MATCHING PRICE & PRODUCT COLUMNS)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY DEFAULT ('ORD-' || floor(random() * 90000 + 10000)::text),
  customer_name TEXT NOT NULL DEFAULT 'Customer',
  email TEXT,
  phone TEXT NOT NULL DEFAULT '',
  city TEXT DEFAULT 'Unspecified',
  address TEXT NOT NULL DEFAULT '',
  category TEXT DEFAULT 'General',
  product_variant TEXT NOT NULL DEFAULT 'Standard Product',
  product_id BIGINT,
  quantity INTEGER NOT NULL DEFAULT 1,
  
  -- Matching Price Columns with Products schema
  price NUMERIC DEFAULT 0,
  sale_price NUMERIC DEFAULT 0,
  price_per_unit NUMERIC DEFAULT 0,
  mrp NUMERIC DEFAULT 0,
  amount NUMERIC NOT NULL DEFAULT 0, -- Total Order & COD price
  cod_amount NUMERIC DEFAULT 0,
  
  -- Order Logistics & Status
  status TEXT NOT NULL DEFAULT 'pending',
  payment_method TEXT DEFAULT 'Cash on Delivery (COD)',
  tracking_number TEXT,
  notes TEXT,
  -- Shared storefront-compatible columns (my B shoppy frontend online payment)
  country TEXT DEFAULT '',
  product_name TEXT,
  total_amount NUMERIC DEFAULT 0,
  items_summary TEXT,
  razorpay_order_id TEXT,
  razorpay_payment_id TEXT,
  razorpay_signature TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Ensure all order columns exist safely (idempotent migration)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='customer_name') THEN
    ALTER TABLE public.orders ADD COLUMN customer_name TEXT DEFAULT 'Customer';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='email') THEN
    ALTER TABLE public.orders ADD COLUMN email TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='phone') THEN
    ALTER TABLE public.orders ADD COLUMN phone TEXT DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='city') THEN
    ALTER TABLE public.orders ADD COLUMN city TEXT DEFAULT 'Unspecified';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='address') THEN
    ALTER TABLE public.orders ADD COLUMN address TEXT DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='category') THEN
    ALTER TABLE public.orders ADD COLUMN category TEXT DEFAULT 'General';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='product_variant') THEN
    ALTER TABLE public.orders ADD COLUMN product_variant TEXT DEFAULT 'Standard Product';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='product_id') THEN
    ALTER TABLE public.orders ADD COLUMN product_id BIGINT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='quantity') THEN
    ALTER TABLE public.orders ADD COLUMN quantity INTEGER DEFAULT 1;
  END IF;
  
  -- Price columns in orders table
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='price') THEN
    ALTER TABLE public.orders ADD COLUMN price NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='sale_price') THEN
    ALTER TABLE public.orders ADD COLUMN sale_price NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='price_per_unit') THEN
    ALTER TABLE public.orders ADD COLUMN price_per_unit NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='mrp') THEN
    ALTER TABLE public.orders ADD COLUMN mrp NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='amount') THEN
    ALTER TABLE public.orders ADD COLUMN amount NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='cod_amount') THEN
    ALTER TABLE public.orders ADD COLUMN cod_amount NUMERIC DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='status') THEN
    ALTER TABLE public.orders ADD COLUMN status TEXT DEFAULT 'pending';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='payment_method') THEN
    ALTER TABLE public.orders ADD COLUMN payment_method TEXT DEFAULT 'Cash on Delivery (COD)';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='tracking_number') THEN
    ALTER TABLE public.orders ADD COLUMN tracking_number TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='notes') THEN
    ALTER TABLE public.orders ADD COLUMN notes TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='country') THEN
    ALTER TABLE public.orders ADD COLUMN country TEXT DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='product_name') THEN
    ALTER TABLE public.orders ADD COLUMN product_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='total_amount') THEN
    ALTER TABLE public.orders ADD COLUMN total_amount NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='items_summary') THEN
    ALTER TABLE public.orders ADD COLUMN items_summary TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='razorpay_order_id') THEN
    ALTER TABLE public.orders ADD COLUMN razorpay_order_id TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='razorpay_payment_id') THEN
    ALTER TABLE public.orders ADD COLUMN razorpay_payment_id TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='razorpay_signature') THEN
    ALTER TABLE public.orders ADD COLUMN razorpay_signature TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='created_at') THEN
    ALTER TABLE public.orders ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='updated_at') THEN
    ALTER TABLE public.orders ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();
  END IF;
END $$;


-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- ==============================================================================
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Grant permissions to standard Supabase API roles
GRANT ALL ON TABLE public.products TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.orders TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Products Policies
DROP POLICY IF EXISTS "Allow public read access on products" ON public.products;
CREATE POLICY "Allow public read access on products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access on products" ON public.products;
CREATE POLICY "Allow public insert access on products" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access on products" ON public.products;
CREATE POLICY "Allow public update access on products" ON public.products FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete access on products" ON public.products;
CREATE POLICY "Allow public delete access on products" ON public.products FOR DELETE USING (true);

-- Orders Policies
DROP POLICY IF EXISTS "Allow public read access on orders" ON public.orders;
CREATE POLICY "Allow public read access on orders" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access on orders" ON public.orders;
CREATE POLICY "Allow public insert access on orders" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access on orders" ON public.orders;
CREATE POLICY "Allow public update access on orders" ON public.orders FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete access on orders" ON public.orders;
CREATE POLICY "Allow public delete access on orders" ON public.orders FOR DELETE USING (true);


-- ==============================================================================
-- 5. ENABLE REALTIME BROADCASTING
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'products'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
EXCEPTION
  WHEN others THEN NULL;
END $$;

-- 6. Notify PostgREST to reload schema cache immediately
NOTIFY pgrst, 'reload schema';
`;

export const SUPABASE_PRODUCTS_TABLE_SQL = SUPABASE_UNIFIED_SCHEMA_SQL;

const LOCAL_STORAGE_PRODUCTS_KEY = 'mybshoppy_products_catalog_manual_v1';

export function getCachedProducts(): Product[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_PRODUCTS_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) {
        return parsed;
      }
    }
  } catch (e) {
    console.error('Failed to read cached products', e);
  }
  return [];
}

function compactProductsForStorage(products: Product[], aggressive = false): Product[] {
  return products.map((p) => {
    const out: any = { ...p };
    if (typeof out.description === 'string' && out.description.length > 400) {
      out.description = out.description.slice(0, 400);
    }
    if (typeof out.material === 'string' && out.material.length > 200) {
      out.material = out.material.slice(0, 200);
    }
    const img = out.cover_image;
    if (typeof img === 'string') {
      if (aggressive) {
        out.cover_image = img.startsWith('data:') ? '' : img;
      } else if (img.startsWith('data:') && img.length > 4000) {
        out.cover_image = '';
      }
    }
    return out;
  });
}

export function saveCachedProducts(products: Product[]) {
  try {
    const payload = JSON.stringify(compactProductsForStorage(products));
    try {
      localStorage.setItem(LOCAL_STORAGE_PRODUCTS_KEY, payload);
      return;
    } catch {
      localStorage.setItem(
        LOCAL_STORAGE_PRODUCTS_KEY,
        JSON.stringify(compactProductsForStorage(products, true))
      );
    }
  } catch {
    // Best-effort cache: leave existing cache untouched rather than spamming the console
  }
}

/**
 * Checks if an ID string/number is a valid database primary key (integer or UUID)
 */
export function isValidDatabaseId(id: string | number | undefined | null): boolean {
  if (typeof id === 'number') return true;
  if (!id || typeof id !== 'string') return false;
  // Numeric integer ID (e.g. "1", "42", "1002")
  if (/^\d+$/.test(id)) return true;
  // UUID (e.g. "123e4567-e89b-12d3-a456-426614174000")
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(id);
}

/**
 * Generates a standard RFC4122 compliant UUID v4 string
 */
export function generateClientUuid(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    try {
      return crypto.randomUUID();
    } catch {
      // fallback
    }
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Extracts unrecognized/missing column name from Supabase/PostgREST error messages
 */
function extractMissingColumn(errorMessage?: string): string | null {
  if (!errorMessage) return null;
  // 1. PostgREST: Could not find the 'cover_image' column of 'products' in the schema cache
  const postgrestMatch = errorMessage.match(/Could not find the ['"]?([a-zA-Z0-9_]+)['"]? column of/i);
  if (postgrestMatch && postgrestMatch[1]) return postgrestMatch[1];

  // 2. Postgres: column "cover_image" of relation "products" does not exist
  const pgMatch1 = errorMessage.match(/column ["']?([a-zA-Z0-9_]+)["']? of relation/i);
  if (pgMatch1 && pgMatch1[1]) return pgMatch1[1];

  // 3. Postgres: column "cover_image" does not exist
  const pgMatch2 = errorMessage.match(/column ["']?([a-zA-Z0-9_]+)["']? does not exist/i);
  if (pgMatch2 && pgMatch2[1]) return pgMatch2[1];

  return null;
}

/**
 * Extracts column name that triggered a NOT-NULL constraint violation
 */
function extractNotNullColumn(errorMessage?: string): string | null {
  if (!errorMessage) return null;
  // Postgres: null value in column "name" of relation "products" violates not-null constraint
  const match = errorMessage.match(/null value in column ["']?([a-zA-Z0-9_]+)["']? (?:of relation|violates not-null)/i);
  if (match && match[1]) return match[1];

  const match2 = errorMessage.match(/violates not-null constraint.*column ["']?([a-zA-Z0-9_]+)["']?/i);
  if (match2 && match2[1]) return match2[1];

  return null;
}

/**
 * Fetch all products from Supabase 'products' table (with fallback to local storage)
 */
export async function getProducts(): Promise<{ products: Product[]; error?: string; source: 'supabase' | 'cache' }> {
  try {
    let data: any[] | null = null;
    let error: any = null;

    // 1. Try ordered fetch
    const firstAttempt = await supabase
      .from('products')
      .select('*')
      .order('created_at', { ascending: false });

    data = firstAttempt.data;
    error = firstAttempt.error;

    // 2. If ordering by created_at failed due to missing column, try simple select
    if (error && (error.message.includes('created_at') || extractMissingColumn(error.message))) {
      const secondAttempt = await supabase
        .from('products')
        .select('*');
      data = secondAttempt.data;
      error = secondAttempt.error;
    }

    if (error) {
      console.warn('Supabase products fetch warning/error (using cache):', error.message);
      const cached = getCachedProducts();
      return { products: cached, error: error.message, source: 'cache' };
    }

    if (data && data.length > 0) {
      const normalized: Product[] = data.map((item) => {
        let parsedBadges: string[] = [];
        if (Array.isArray(item.badges)) {
          parsedBadges = item.badges;
        } else if (typeof item.badges === 'string') {
          try {
            parsedBadges = JSON.parse(item.badges);
          } catch {
            parsedBadges = item.badges.split(',').map((s: string) => s.trim()).filter(Boolean);
          }
        }

        return {
          id: item.id || item.slug || generateClientUuid(),
          title: item.title || item.name || 'Untitled Product',
          sku: item.sku || `SKU-${Math.floor(100 + Math.random() * 900)}`,
          category: item.category || 'Jewellery',
          cover_image: item.cover_image || item.image_url || item.image || PRESET_JEWELLERY_IMAGES[0].url,
          mrp: Number(item.mrp) || Number(item.price) || Number(item.sale_price) || 0,
          sale_price: Number(item.sale_price) || Number(item.price) || 0,
          quantity: Number(item.quantity ?? item.stock ?? (item.in_stock === false ? 0 : 1)),
          badges: Array.isArray(parsedBadges) ? parsedBadges : [],
          slug: item.slug || undefined,
          subtitle: item.subtitle || '',
          original_price: item.original_price ? Number(item.original_price) : undefined,
          category_id: item.category_id || undefined,
          badge: item.badge || undefined,
          rating: item.rating ? Number(item.rating) : undefined,
          reviews_count: item.reviews_count ? Number(item.reviews_count) : undefined,
          stone: item.stone || undefined,
          variants: Array.isArray(item.variants) ? item.variants : undefined,
          in_stock: typeof item.in_stock === 'boolean' ? item.in_stock : Number(item.quantity ?? item.stock) > 0,
          description: item.description || '',
          material: item.material || '',
          created_at: item.created_at || new Date().toISOString(),
          updated_at: item.updated_at,
        };
      });

      saveCachedProducts(normalized);
      return { products: normalized, source: 'supabase' };
    }

    // Empty table
    const cached = getCachedProducts();
    saveCachedProducts(cached);
    return { products: cached, source: 'cache' };
  } catch (err: any) {
    console.error('Network exception fetching products:', err);
    const cached = getCachedProducts();
    return { products: cached, error: err.message, source: 'cache' };
  }
}

/**
 * Helper to attempt resilient insertion with adaptive column fallbacks
 */
async function attemptInsertProductToSupabase(productData: Omit<Product, 'id'>): Promise<{ data: any; error: any }> {
  const salePrice = Number(productData.sale_price) || 0;
  const mrp = Number(productData.mrp) || salePrice;
  const quantity = Number(productData.quantity) || 0;
  const coverImage = productData.cover_image || '';
  const badges = productData.badges || [];

  // Helper to generate a default value for any required/not-null column
  const getColValue = (col: string) => {
    switch (col) {
      case 'title':
      case 'name':
        return productData.title || 'Jewellery Item';
      case 'sku':
        return productData.sku || `SKU-${Date.now().toString().slice(-4)}`;
      case 'category':
        return productData.category || 'Jewellery';
      case 'cover_image':
      case 'image_url':
      case 'image':
        return coverImage || 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80';
      case 'sale_price':
      case 'price':
        return salePrice;
      case 'mrp':
        return mrp;
      case 'quantity':
      case 'stock':
        return quantity;
      case 'badges':
        return badges;
      case 'description':
        return productData.description || '';
      case 'material':
        return productData.material || '';
      default:
        return '';
    }
  };

  // Start with full standard payload including both title and name
  let payload: Record<string, any> = {
    title: productData.title,
    name: productData.title,
    sku: productData.sku,
    category: productData.category,
    cover_image: coverImage,
    image_url: coverImage,
    mrp: mrp,
    sale_price: salePrice,
    price: salePrice,
    quantity: quantity,
    stock: quantity,
    badges: badges,
    description: productData.description || '',
    material: productData.material || '',
    slug: productData.slug || `${productData.title || 'item'}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || undefined,
    subtitle: productData.subtitle || '',
    original_price: productData.original_price ? Number(productData.original_price) : null,
    category_id: productData.category_id || (productData.category ? productData.category.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') : null),
    badge: productData.badge || (productData.badges && productData.badges[0]) || null,
    rating: productData.rating ? Number(productData.rating) : 5.0,
    reviews_count: productData.reviews_count ? Number(productData.reviews_count) : 0,
    stone: productData.stone || null,
    variants: Array.isArray(productData.variants) && productData.variants.length > 0 ? productData.variants : ['Standard'],
    in_stock: quantity > 0,
  };

  const triedMissingCols = new Set<string>();
  const satisfiedNotNullCols = new Set<string>();
  let lastError: any = null;

  // Adaptive retry loop (up to 12 iterations)
  for (let attempt = 0; attempt < 12; attempt++) {
    try {
      const { data, error } = await supabase
        .from('products')
        .insert([payload])
        .select()
        .single();

      if (!error && data) {
        return { data, error: null };
      }

      if (error) {
        lastError = error;

        // 1. Check for NOT-NULL constraint violation
        const notNullCol = extractNotNullColumn(error.message);
        if (notNullCol && !satisfiedNotNullCols.has(notNullCol)) {
          satisfiedNotNullCols.add(notNullCol);
          payload[notNullCol] = getColValue(notNullCol);
          continue;
        }

        // 2. Check for missing column in schema cache
        const missingCol = extractMissingColumn(error.message);
        if (missingCol && !triedMissingCols.has(missingCol)) {
          triedMissingCols.add(missingCol);
          delete payload[missingCol];

          // If payload still has at least 1 field, retry
          if (Object.keys(payload).length > 0) {
            continue;
          }
        }

        // If specific column couldn't be extracted, try simpler fallback presets
        break;
      }
    } catch (e: any) {
      lastError = e;
      break;
    }
  }

  // Fallback simple payload attempts
  const fallbackPayloads = [
    { name: productData.title, price: salePrice, stock: quantity, category: productData.category },
    { title: productData.title, price: salePrice, quantity: quantity },
    { name: productData.title, price: salePrice },
    { title: productData.title, price: salePrice },
    { name: productData.title },
    { title: productData.title }
  ];

  for (const fb of fallbackPayloads) {
    try {
      const { data, error } = await supabase
        .from('products')
        .insert([fb])
        .select()
        .single();
      if (!error && data) {
        return { data, error: null };
      }
    } catch {
      // Continue
    }
  }

  return { data: null, error: lastError };
}

/**
 * Create a new product in Supabase and local cache
 */
export async function createProduct(
  productData: Omit<Product, 'id'>
): Promise<{ success: boolean; product?: Product; error?: string; isDatabaseError?: boolean }> {
  try {
    const fallbackId = generateClientUuid();
    const newRecord: Product = {
      ...productData,
      id: fallbackId,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    // 1. Attempt Supabase insertion with adaptive fallbacks
    const { data, error } = await attemptInsertProductToSupabase(productData);

    const createdProduct: Product = data
      ? {
          id: data.id || data.slug || fallbackId,
          title: data.title || data.name || productData.title,
          sku: data.sku || productData.sku,
          category: data.category || productData.category,
          cover_image: data.cover_image || data.image_url || data.image || productData.cover_image,
          mrp: Number(data.mrp) || Number(productData.mrp) || Number(productData.sale_price),
          sale_price: Number(data.sale_price) || Number(data.price) || Number(productData.sale_price),
          quantity: Number(data.quantity ?? data.stock ?? productData.quantity),
          badges: Array.isArray(data.badges) ? data.badges : productData.badges,
          slug: data.slug || productData.slug,
          subtitle: data.subtitle || productData.subtitle || '',
          original_price: data.original_price ? Number(data.original_price) : productData.original_price,
          category_id: data.category_id || productData.category_id,
          badge: data.badge || productData.badge,
          rating: data.rating ? Number(data.rating) : productData.rating,
          reviews_count: data.reviews_count ? Number(data.reviews_count) : productData.reviews_count,
          stone: data.stone || productData.stone,
          variants: Array.isArray(data.variants) ? data.variants : productData.variants,
          in_stock: typeof data.in_stock === 'boolean' ? data.in_stock : (productData.quantity || 0) > 0,
          description: data.description || productData.description,
          material: data.material || productData.material,
          created_at: data.created_at || newRecord.created_at,
          updated_at: data.updated_at || newRecord.updated_at,
        }
      : newRecord;

    // 2. Update local cache
    const current = getCachedProducts();
    saveCachedProducts([createdProduct, ...current]);

    if (error) {
      console.error('Supabase product insertion failed:', error);
      return {
        success: false,
        product: createdProduct,
        error: error.message || 'Supabase database rejected the product insert.',
        isDatabaseError: true,
      };
    }

    return { success: true, product: createdProduct };
  } catch (err: any) {
    console.error('Error creating product:', err);
    const fallback: Product = {
      ...productData,
      id: generateClientUuid(),
      created_at: new Date().toISOString(),
    };
    const current = getCachedProducts();
    saveCachedProducts([fallback, ...current]);
    return {
      success: false,
      product: fallback,
      error: err.message || 'Network exception while storing product.',
      isDatabaseError: true,
    };
  }
}

/**
 * Update existing product in Supabase and local cache
 */
export async function updateProduct(
  id: string | number,
  updates: Partial<Product>
): Promise<{ success: boolean; product?: Product; error?: string; isDatabaseError?: boolean }> {
  try {
    const current = getCachedProducts();
    const existing = current.find((p) => String(p.id) === String(id));

    const salePrice = updates.sale_price !== undefined ? Number(updates.sale_price) : undefined;
    const mrp = updates.mrp !== undefined ? Number(updates.mrp) : undefined;
    const quantity = updates.quantity !== undefined ? Number(updates.quantity) : undefined;

    let updatePayload: any = {
      updated_at: new Date().toISOString(),
    };
    if (updates.title !== undefined) {
      updatePayload.title = updates.title;
      updatePayload.name = updates.title;
    }
    if (updates.sku !== undefined) updatePayload.sku = updates.sku;
    if (updates.category !== undefined) updatePayload.category = updates.category;
    if (updates.cover_image !== undefined) {
      updatePayload.cover_image = updates.cover_image;
      updatePayload.image_url = updates.cover_image;
    }
    if (salePrice !== undefined) {
      updatePayload.sale_price = salePrice;
      updatePayload.price = salePrice;
    }
    if (mrp !== undefined) updatePayload.mrp = mrp;
    if (quantity !== undefined) {
      updatePayload.quantity = quantity;
      updatePayload.stock = quantity;
      updatePayload.in_stock = quantity > 0;
    }
    if (updates.badges !== undefined) updatePayload.badges = updates.badges;
    if (updates.description !== undefined) updatePayload.description = updates.description;
    if (updates.material !== undefined) updatePayload.material = updates.material;
    if (updates.subtitle !== undefined) updatePayload.subtitle = updates.subtitle;
    if (updates.original_price !== undefined) updatePayload.original_price = updates.original_price;
    if (updates.category_id !== undefined) updatePayload.category_id = updates.category_id;
    if (updates.badge !== undefined) updatePayload.badge = updates.badge;
    if (updates.rating !== undefined) updatePayload.rating = updates.rating;
    if (updates.reviews_count !== undefined) updatePayload.reviews_count = updates.reviews_count;
    if (updates.stone !== undefined) updatePayload.stone = updates.stone;
    if (updates.variants !== undefined) updatePayload.variants = updates.variants;
    if (updates.in_stock !== undefined) updatePayload.in_stock = updates.in_stock;

    let targetDbId: string | number | null = isValidDatabaseId(id) ? id : null;

    // If id is synthetic (e.g. "PRD-951010"), search Supabase for real record by SKU or title
    if (!targetDbId) {
      const skuToSearch = updates.sku || existing?.sku;
      if (skuToSearch) {
        const { data: foundBySku } = await supabase
          .from('products')
          .select('id')
          .eq('sku', skuToSearch)
          .maybeSingle();
        if (foundBySku?.id) {
          targetDbId = foundBySku.id;
        }
      }
      if (!targetDbId && (updates.title || existing?.title)) {
        const titleToSearch = updates.title || existing?.title;
        const { data: foundByTitle } = await supabase
          .from('products')
          .select('id')
          .eq('title', titleToSearch)
          .maybeSingle();
        if (foundByTitle?.id) {
          targetDbId = foundByTitle.id;
        }
      }
    }

    // If still no database record exists, insert it into Supabase now as a newly synced product
    if (!targetDbId) {
      const fullData: Omit<Product, 'id'> = {
        title: updates.title || existing?.title || 'Jewellery Item',
        sku: updates.sku || existing?.sku || `SKU-${Date.now().toString().slice(-4)}`,
        category: updates.category || existing?.category || 'Jewellery',
        cover_image: updates.cover_image || existing?.cover_image || '',
        mrp: updates.mrp !== undefined ? updates.mrp : (existing?.mrp || 0),
        sale_price: updates.sale_price !== undefined ? updates.sale_price : (existing?.sale_price || 0),
        quantity: updates.quantity !== undefined ? updates.quantity : (existing?.quantity || 0),
        badges: updates.badges || existing?.badges || [],
        description: updates.description !== undefined ? updates.description : (existing?.description || ''),
        material: updates.material !== undefined ? updates.material : (existing?.material || ''),
      };

      const insertRes = await attemptInsertProductToSupabase(fullData);
      const newDbId = insertRes.data?.id || generateClientUuid();

      const mergedProduct: Product = {
        ...fullData,
        id: newDbId,
        created_at: insertRes.data?.created_at || existing?.created_at || new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      const updatedList = current.map((p) => (String(p.id) === String(id) ? mergedProduct : p));
      saveCachedProducts(updatedList);

      return { success: true, product: mergedProduct };
    }

    let data: any = null;
    let error: any = null;
    const triedUpdateCols = new Set<string>();

    for (let attempt = 0; attempt < 8; attempt++) {
      const res = await supabase
        .from('products')
        .update(updatePayload)
        .eq('id', targetDbId)
        .select()
        .single();

      data = res.data;
      error = res.error;

      if (!error && data) {
        break;
      }

      if (error) {
        // If error is invalid input syntax for UUID/type, attempt fallback
        if (error.code === '22P02' || error.message?.includes('invalid input syntax for type uuid')) {
          break;
        }

        const missingCol = extractMissingColumn(error.message);
        if (missingCol && !triedUpdateCols.has(missingCol)) {
          triedUpdateCols.add(missingCol);
          if (missingCol === 'cover_image' && updates.cover_image) {
            delete updatePayload.cover_image;
            updatePayload.image_url = updates.cover_image;
          } else if (missingCol === 'image_url') {
            delete updatePayload.image_url;
            delete updatePayload.cover_image;
          } else if (missingCol === 'sale_price' && salePrice !== undefined) {
            delete updatePayload.sale_price;
            updatePayload.price = salePrice;
          } else if (missingCol === 'price') {
            delete updatePayload.price;
            delete updatePayload.sale_price;
          } else if (missingCol === 'quantity' && quantity !== undefined) {
            delete updatePayload.quantity;
            updatePayload.stock = quantity;
          } else if (missingCol === 'stock') {
            delete updatePayload.stock;
            delete updatePayload.quantity;
          } else if (missingCol === 'title' && updates.title) {
            delete updatePayload.title;
            updatePayload.name = updates.title;
          } else if (missingCol === 'name') {
            delete updatePayload.name;
            delete updatePayload.title;
          } else {
            delete updatePayload[missingCol];
          }

          if (Object.keys(updatePayload).length > 0) {
            continue;
          }
        }
        break;
      }
    }

    // Update local cache
    let updatedProduct: Product | undefined;
    const finalId = targetDbId || id;
    const updatedList = current.map((p) => {
      if (String(p.id) === String(id) || String(p.id) === String(targetDbId)) {
        updatedProduct = {
          ...p,
          ...updates,
          id: finalId,
          updated_at: new Date().toISOString(),
        };
        return updatedProduct;
      }
      return p;
    });

    saveCachedProducts(updatedList);

    if (error) {
      console.error('Supabase update product error:', error);
      return {
        success: false,
        product: updatedProduct,
        error: error.message,
        isDatabaseError: true,
      };
    }

    return { success: true, product: data || updatedProduct };
  } catch (err: any) {
    console.error('Error updating product:', err);
    const current = getCachedProducts();
    let updatedProduct: Product | undefined;
    const updatedList = current.map((p) => {
      if (String(p.id) === String(id)) {
        updatedProduct = { ...p, ...updates, updated_at: new Date().toISOString() };
        return updatedProduct;
      }
      return p;
    });
    saveCachedProducts(updatedList);
    return { success: false, product: updatedProduct, error: err.message, isDatabaseError: true };
  }
}

/**
 * Reduce a product's available stock after an order is created.
 * Keeps `quantity`, `stock`, and `in_stock` in sync so both the admin
 * dashboard and the front store immediately show the reduced stock.
 */
export async function decrementProductStock(
  productId: string | number | undefined | null,
  orderedQty: number
): Promise<{ success: boolean; product?: Product; error?: string }> {
  try {
    if (productId === undefined || productId === null || String(productId) === 'CUSTOM') {
      return { success: false, error: 'No catalog product linked to this order.' };
    }

    const qtyToDeduct = Math.max(1, Math.round(Number(orderedQty) || 1));
    const cached = getCachedProducts();
    const cachedProduct = cached.find((p) => String(p.id) === String(productId));

    // 1. Locate the matching Supabase row
    let targetDbId: string | number | null = isValidDatabaseId(productId) ? productId : null;
    let dbRow: any = null;

    if (targetDbId) {
      const res = await supabase
        .from('products')
        .select('id, quantity, stock, in_stock')
        .eq('id', targetDbId)
        .maybeSingle();
      dbRow = res.data;
    }

    // Synthetic ids (PRD-xxxx / uuid): resolve the real row via SKU or title
    if (!dbRow && cachedProduct) {
      const matchField: [string, string] | null = cachedProduct.sku
        ? ['sku', cachedProduct.sku]
        : cachedProduct.title
        ? ['title', cachedProduct.title]
        : null;
      if (matchField) {
        const res = await supabase
          .from('products')
          .select('id, quantity, stock, in_stock')
          .eq(matchField[0], matchField[1])
          .maybeSingle();
        dbRow = res.data;
        if (dbRow?.id) targetDbId = dbRow.id;
      }
    }

    // 2. Compute the new stock level (DB value wins over the local cache)
    const currentStock =
      dbRow && (dbRow.quantity !== null || dbRow.stock !== null)
        ? Number(dbRow.quantity ?? dbRow.stock) || 0
        : Number(cachedProduct?.quantity) || 0;
    const newStock = Math.max(0, currentStock - qtyToDeduct);

    // 3. Write it back, retrying if a column is missing from the live schema
    let updateError: any = null;
    if (targetDbId) {
      const payload: any = {
        quantity: newStock,
        stock: newStock,
        in_stock: newStock > 0,
        updated_at: new Date().toISOString(),
      };
      const droppedCols = new Set<string>();

      for (let attempt = 0; attempt < 5; attempt++) {
        const res = await supabase
          .from('products')
          .update(payload)
          .eq('id', targetDbId)
          .select()
          .single();
        if (!res.error && res.data) {
          updateError = null;
          break;
        }
        updateError = res.error;
        const missingCol = updateError ? extractMissingColumn(updateError.message) : null;
        if (!missingCol || droppedCols.has(missingCol)) break;
        droppedCols.add(missingCol);
        if (missingCol === 'quantity') payload.stock = newStock;
        if (missingCol === 'stock') payload.quantity = newStock;
        delete payload[missingCol];
        if (Object.keys(payload).length === 0) break;
      }
    }

    // 4. Mirror the change in the local cache for an instant UI update
    let updatedProduct: Product | undefined;
    const updatedList = cached.map((p) => {
      if (String(p.id) === String(productId)) {
        updatedProduct = {
          ...p,
          quantity: newStock,
          in_stock: newStock > 0,
          updated_at: new Date().toISOString(),
        };
        return updatedProduct;
      }
      return p;
    });
    saveCachedProducts(updatedList);

    if (updateError) {
      console.error('Supabase stock reduction error:', updateError.message);
      return { success: false, product: updatedProduct, error: updateError.message };
    }
    if (!targetDbId && !cachedProduct) {
      return { success: false, error: 'Product not found for stock reduction.' };
    }

    return { success: true, product: updatedProduct };
  } catch (err: any) {
    console.error('Error decrementing product stock:', err);
    return { success: false, error: err.message || 'Failed to reduce stock.' };
  }
}

/**
 * Delete a product from Supabase and local cache
 */
export async function deleteProduct(id: string | number): Promise<{ success: boolean; error?: string }> {
  try {
    const current = getCachedProducts();
    const existing = current.find((p) => String(p.id) === String(id));

    let error: any = null;

    if (isValidDatabaseId(id)) {
      const res = await supabase
        .from('products')
        .delete()
        .eq('id', id);
      error = res.error;
    } else if (existing?.sku) {
      // Synthetic id: delete by SKU from Supabase if present
      const res = await supabase
        .from('products')
        .delete()
        .eq('sku', existing.sku);
      error = res.error;
    }

    const filtered = current.filter((p) => String(p.id) !== String(id));
    saveCachedProducts(filtered);

    if (error) {
      console.warn('Supabase delete error:', error.message);
      return { success: false, error: error.message };
    }
    return { success: true };
  } catch (err: any) {
    console.error('Error deleting product:', err);
    const current = getCachedProducts();
    const filtered = current.filter((p) => String(p.id) !== String(id));
    saveCachedProducts(filtered);
    return { success: false, error: err.message };
  }
}

/**
 * Duplicate a product
 */
export async function duplicateProduct(
  id: string | number
): Promise<{ success: boolean; product?: Product; error?: string; isDatabaseError?: boolean }> {
  const current = getCachedProducts();
  const source = current.find((p) => String(p.id) === String(id));
  if (!source) {
    return { success: false, error: 'Source product not found' };
  }

  const duplicatedData: Omit<Product, 'id'> = {
    title: `${source.title} (Copy)`,
    sku: `${source.sku}-COPY`,
    category: source.category,
    cover_image: source.cover_image,
    mrp: source.mrp,
    sale_price: source.sale_price,
    quantity: source.quantity,
    badges: [...source.badges],
    description: source.description,
    material: source.material,
  };

  return createProduct(duplicatedData);
}

/**
 * Compute product statistics
 */
export function computeProductStats(products: Product[]): ProductStats {
  const categories = new Set<string>();
  let totalUnits = 0;
  let totalValue = 0;
  let lowStock = 0;
  let outOfStock = 0;
  let bestsellers = 0;

  products.forEach((p) => {
    if (p.category) categories.add(p.category);
    const qty = Number(p.quantity) || 0;
    const price = Number(p.sale_price) || Number(p.mrp) || 0;
    totalUnits += qty;
    totalValue += qty * price;

    if (qty === 0) {
      outOfStock += 1;
    } else if (qty <= 15) {
      lowStock += 1;
    }

    if (p.badges && p.badges.includes('Bestseller')) {
      bestsellers += 1;
    }
  });

  return {
    totalProducts: products.length,
    totalInventoryUnits: totalUnits,
    totalCatalogValue: totalValue,
    lowStockCount: lowStock,
    outOfStockCount: outOfStock,
    categoriesCount: categories.size,
    bestsellersCount: bestsellers,
  };
}
